---
title: (17)Promise封装
category: "ECMAScript"
tags: ["ECMAScript", "ES6"]
description: "Promise封装：单个的异步任务看不出，使用Promise的好处，当异步任务数量太多时，使用Promise会更加方便友好。"
cover: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/blog/md/ES.svg
top_img: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/blog/md/ES.svg
---

***

### Promise封装读取文件

**原始读取方式**


    // 引入fs模块
    const fs = require("fs")
    
    // 调用方法读取文件
    fs.readFile("./resources/为学.md", (err, data) => {
      // 如果错误，则抛出错误
      if(err) throw err;
      // 如果没有出错，则输出内容
      console.log(data.toString())
    })


**使用Promise方式**


    // 引入fs模块
    const fs = require("fs")
    
    // 使用Promise封装
    const p = new Promise(function(resolve, reject){
      fs.readFile("./resources/为学.md", (err, data) => {
        // 如果错误
        if(err) reject(err);
        // 如果成功
        resolve(data)
      })
    })
    p.then(function(value){
      console.log(value.toString())
    }, function(reason){
      console.log("读取失败", reason)
    })


单个的异步任务看不出，使用Promise的好处，当异步任务数量太多时，使用Promise会更加方便友好。

***

### Promise封装ajax

**原生的ajax**。


```js es
<script>
  // 1.创建对象
  const xhr = new XMLHttpRequest();
  
  // 2.初始化
  xhr.open("GET", "https://api.apiopen.top/getJoke")
  
  // 3.发送
  xhr.send()
  
  // 4.绑定事件，处理相应结果
  xhr.onreadystatechange = function(){
    //判断
    if(xhr.readyState === 4){
      //判断相应状态码：根据具体接口规则
      if(xhr.status >= 200 && xhr.status < 300){
        // 一般200-299之间表示成功。
        console.log("成功数据：", xhr.response)
      }else{
        //如果失败
        console.log("错误信息：", xhr.status)
      }
    }
  }
</script>
```


**使用Promise进行封装**。


```js es
<script>
  // Promise封装网络请求
  const p = new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", "https://api.apiopen.top/getJoke")
    xhr.send()
    xhr.onreadystatechange = function(){
      if(xhr.readyState === 4){
        if(xhr.status >= 200 && xhr.status < 300){
          resolve(["成功数据：", xhr.response])
          
        }else{
          reject(["错误信息：", xhr.status])
        }
      }
    }
  })
  // 将页面数据处理的流程分离出来。
  // 这比将数据处理的语句，混淆在网络请求中更清晰。
  p.then(function(value){
    console.log(value)
  }, function(reason){
    console.log(reason)
  })
</script>
```


***

### Promise.prototype.then方法

前面已经知道，使用Promise，在调用then方法时，第一个函数是resolve()时执行的，第二个函数是reject()时执行的。


```js es
<script>
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("用户数据")
    }, 10)
  })
  p.then(function(value){
    console.log(value) // --> 用户数据
  }, function(reason){
    console.log(reason)
  })
</script>
```


通过下面的例子发现，then方法的返回结果也是一个Promise对象。展开看到有一个PromiseStatus的状态为resolve。  


```js es
<script>
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("用户数据")
    }, 10)
  })
  let result = p.then(function(value){
    console.log(value) // --> 用户数据
  }, function(reason){
    console.log(reason)
  })
  
  console.log(result)
  // then方法的返回结果也是一个Promise对象
  // [[PromiseStatus]]:resolve
  // [[PromiseValue]]:undefined
</script>
```


**PromiseStatus的状态，是由回调函数的执行结果来决定**

1.如果回调函数中返回的结果，是一个非Promise类型的数据，状态为即成功resolve。result这个对象的PromiseValue就是return的非Promise值。


    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("用户数据")
      }, 1000)
    })
    let result = p.then(function(value){
      console.log(value) // --> 用户数据
      return "123"  ─────────────────────┐
    }, function(reason){                 |
      console.log(reason)                |
    })                                   |
                                         |
    console.log(result)                  |
    // [[PromiseStatus]]:resolve  <──────┤
    // [[PromiseValue]]:123 <────────────┘


2.如果回调函数中返回的结果，是一个Promise类型的数据。


    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("用户数据")
      }, 1000)
    })
    let result = p.then(function(value){
                     └──────────────────┐
      // return 返回的Promise状态，决定了then方法返回的状态。
                        └─────────────────────────┐
      return new Promise((resolve, reject) => {   |
        resolve("OK") <───────────────────────────┤ 
      })                                          |
    }, function(reason){                          |
      console.log(reason)                         | 
    })                                            |
                                                  |
    console.log(result)                           |
    // [[PromiseStatus]]:resolve  <───────────────┤
    // [[PromiseValue]]:OK <──────────────────────┘


.


    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("用户数据")
      }, 1000)
    })
    let result = p.then(function(value){
                     └──────────────────┐
      // return 返回的Promise状态，决定了then方法返回的状态。
                        └─────────────────────────┐
      return new Promise((resolve, reject) => {   |
        reject("error") <─────────────────────────┤ 
      })                                          |
    }, function(reason){                          |
      console.log(reason)                         | 
    })                                            |
                                                  |
    console.log(result)                           |
    // [[PromiseStatus]]:rejected  <──────────────┤
    // [[PromiseValue]]:error <───────────────────┘


3.如果主动抛出错误


    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("用户数据")
      }, 1000)
    })
    let result = p.then(function(value){
                     └─────────┐
      // 主动抛出错误，也会改变then方法返回的状态。
                               └──────────────────┐
        throw new Error("出错了！") <──────────────┤ 
    }, function(reason){                          |
      console.log(reason)                         | 
    })                                            |
                                                  |
    console.log(result)                           |
    // [[PromiseStatus]]:rejected  <──────────────┤
    // [[PromiseValue]]: 出错了！  <───────────────┘


**链式调用**。


    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("用户数据")
      }, 1000)
    })
    p.then(function(value){
      return new Promise((resolve, reject) => {
        ...新的异步操作
        resolve()
      })
    }).then(function(value){
      
    })


***

### Promise多个文件读取

**原始的方式**


    const fs = require("fs")
    
    fs.readFile("./resources/为学.md", (err, data1) => {
      fs.readFile("./resources/插秧诗.md", (err, data2) => {
        fs.readFile("./resources/观书有感.md", (err, data3) => {
          let result = data1 + "\r\n" + data2 + "\r\n" + data3
          console.log(result)
        })
      })
    })


**Promise的方式**


    const fs = require("fs")
    
    const p = new Promise((resolve, reject) => {
      fs.readFile("./resources/为学.md", (err, data) => {
        resolve(data)
      })
    })
    p.then(value => {
      return new Promise((resolve, reject) => {
        fs.readFile("./resources/插秧诗.md", (err, data) => {
          resolve([value, data])
        })
      })
    }).then(value => {
      return new Promise((resolve, reject) => {
        fs.readFile("./resources/观书有感.md", (err, data) => {
          value.push(data)
          resolve(value)
        })
      })
    }).then(value => {
      console.log(value.join("\r\n"))
    })


***

### Promise对象catch方法

**指定Promise对象回调失败的回调**。


```js es
<script>
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      // 设置p对象的状态为失败
      reject("出错了")
    }, 10)
  })
  p.then(function(value){}, function(reason){
    console.log(reason) // --> 出错了
  })
</script>
```

**通过catch方法**。


```js es
<script>
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      // 设置p对象的状态为失败
      reject("出错了")
    }, 10)
  })
  p.catch(function(reason){
    console.log(reason) // --> 出错了
  })
</script>
```


***

[源：https://www.bilibili.com/video/BV1uK411H7on?p=25](https://www.bilibili.com/video/BV1uK411H7on?p=25)